// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gameProto.proto

#ifndef PROTOBUF_gameProto_2eproto__INCLUDED
#define PROTOBUF_gameProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace lspb {
class CliEnterGame;
class CliEnterGameDefaultTypeInternal;
extern CliEnterGameDefaultTypeInternal _CliEnterGame_default_instance_;
class SrvEnterGame;
class SrvEnterGameDefaultTypeInternal;
extern SrvEnterGameDefaultTypeInternal _SrvEnterGame_default_instance_;
}  // namespace lspb

namespace lspb {

namespace protobuf_gameProto_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_gameProto_2eproto

// ===================================================================

class CliEnterGame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lspb.CliEnterGame) */ {
 public:
  CliEnterGame();
  virtual ~CliEnterGame();

  CliEnterGame(const CliEnterGame& from);

  inline CliEnterGame& operator=(const CliEnterGame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CliEnterGame(CliEnterGame&& from) noexcept
    : CliEnterGame() {
    *this = ::std::move(from);
  }

  inline CliEnterGame& operator=(CliEnterGame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CliEnterGame& default_instance();

  static inline const CliEnterGame* internal_default_instance() {
    return reinterpret_cast<const CliEnterGame*>(
               &_CliEnterGame_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CliEnterGame* other);
  friend void swap(CliEnterGame& a, CliEnterGame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CliEnterGame* New() const PROTOBUF_FINAL { return New(NULL); }

  CliEnterGame* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CliEnterGame& from);
  void MergeFrom(const CliEnterGame& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CliEnterGame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:lspb.CliEnterGame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_gameProto_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SrvEnterGame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lspb.SrvEnterGame) */ {
 public:
  SrvEnterGame();
  virtual ~SrvEnterGame();

  SrvEnterGame(const SrvEnterGame& from);

  inline SrvEnterGame& operator=(const SrvEnterGame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SrvEnterGame(SrvEnterGame&& from) noexcept
    : SrvEnterGame() {
    *this = ::std::move(from);
  }

  inline SrvEnterGame& operator=(SrvEnterGame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SrvEnterGame& default_instance();

  static inline const SrvEnterGame* internal_default_instance() {
    return reinterpret_cast<const SrvEnterGame*>(
               &_SrvEnterGame_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SrvEnterGame* other);
  friend void swap(SrvEnterGame& a, SrvEnterGame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SrvEnterGame* New() const PROTOBUF_FINAL { return New(NULL); }

  SrvEnterGame* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SrvEnterGame& from);
  void MergeFrom(const SrvEnterGame& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SrvEnterGame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:lspb.SrvEnterGame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_gameProto_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CliEnterGame

// -------------------------------------------------------------------

// SrvEnterGame

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace lspb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gameProto_2eproto__INCLUDED
